2018-04-08 12:38:08.275000 Launched python -u C:\Users\Egor\Desktop\kopter\run_folder\main.py
2018-04-08 12:38:08.364000 Init error
2018-04-08 12:38:08.369000 Main run...
2018-04-08 12:38:08.376000 
2018-04-08 12:38:08.461000 Starting threads...
2018-04-08 12:38:08.479000 try update
2018-04-08 12:38:08.492000 Updating...
2018-04-08 12:38:08.572000 Init error
2018-04-08 12:38:08.581000 srv_supervisor_thread start
2018-04-08 12:38:08.588000 srv_supervisor_thread terminated
2018-04-08 12:38:08.593000 Process terminated with exit code 1
2018-04-08 12:38:08.600000 Launched python -u C:\Users\Egor\Desktop\kopter\run_folder\main.py
2018-04-08 12:38:08.668000 Init error
2018-04-08 12:38:08.675000 Main run...
2018-04-08 12:38:08.683000 
2018-04-08 12:38:08.747000 Starting threads...
2018-04-08 12:38:27.948000 try update
2018-04-08 12:38:27.956000 Updating...
2018-04-08 12:38:28.040000 Init error
2018-04-08 12:38:28.062000 srv_supervisor_thread start
2018-04-08 12:38:28.098000 srv_supervisor_thread terminated
2018-04-08 12:38:28.112000 Process terminated with exit code 1
2018-04-08 12:38:28.127000 Launched python -u C:\Users\Egor\Desktop\kopter\run_folder\main.py
2018-04-08 12:38:28.237000 Init error
2018-04-08 12:38:28.245000 Main run...
2018-04-08 12:38:28.253000 
2018-04-08 12:38:28.336000 Starting threads...
2018-04-08 12:38:33.879000 try update
2018-04-08 12:38:33.884000 Updating...
2018-04-08 12:38:33.972000 Process Process-2:
2018-04-08 12:38:33.994000 Init error
2018-04-08 12:38:34.002000 srv_interpreter_thread start
2018-04-08 12:38:34.009000 
2018-04-08 12:38:34.015000 Traceback (most recent call last):
2018-04-08 12:38:34.074000 File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
2018-04-08 12:38:34.155000 self.run()
2018-04-08 12:38:34.170000 File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
2018-04-08 12:38:34.180000 self._target(*self._args, **self._kwargs)
2018-04-08 12:38:34.194000 File "C:\Users\Egor\Desktop\kopter\run_folder\main.py", line 182, in srv_interpreter_thread
2018-04-08 12:38:34.210000 client.close()
2018-04-08 12:38:34.221000 AttributeError: 'str' object has no attribute 'close'
2018-04-08 12:38:34.233000 Init error
2018-04-08 12:38:34.246000 srv_supervisor_thread start
2018-04-08 12:38:34.252000 srv_supervisor_thread terminated
2018-04-08 12:38:34.259000 Process terminated with exit code 1
2018-04-08 12:38:34.266000 Launched python -u C:\Users\Egor\Desktop\kopter\run_folder\main.py
2018-04-08 12:38:34.347000 Init error
2018-04-08 12:38:34.353000 Main run...
2018-04-08 12:38:34.361000 
2018-04-08 12:38:34.437000 Starting threads...
2018-04-08 12:38:52.341000 try update
2018-04-08 12:38:52.347000 Updating...
2018-04-08 12:38:52.355000 Process Process-2:
2018-04-08 12:38:52.368000 Init error
2018-04-08 12:38:52.381000 srv_interpreter_thread start
2018-04-08 12:38:52.387000 
2018-04-08 12:38:52.392000 Traceback (most recent call last):
2018-04-08 12:38:52.398000 File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
2018-04-08 12:38:52.404000 self.run()
2018-04-08 12:38:52.410000 File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
2018-04-08 12:38:52.416000 self._target(*self._args, **self._kwargs)
2018-04-08 12:38:52.421000 File "C:\Users\Egor\Desktop\kopter\run_folder\main.py", line 182, in srv_interpreter_thread
2018-04-08 12:38:52.432000 client.close()
2018-04-08 12:38:52.438000 AttributeError: 'str' object has no attribute 'close'
2018-04-08 12:38:52.445000 Init error
2018-04-08 12:38:52.451000 srv_supervisor_thread start
2018-04-08 12:38:52.457000 srv_supervisor_thread terminated
2018-04-08 12:38:52.467000 Process terminated with exit code 1
2018-04-08 12:38:52.475000 Launched python -u C:\Users\Egor\Desktop\kopter\run_folder\main.py
2018-04-08 12:38:52.556000 Init error
2018-04-08 12:38:52.565000 Main run...
2018-04-08 12:38:52.572000 
2018-04-08 12:38:52.648000 Starting threads...
2018-04-08 12:39:02.613000 try update
2018-04-08 12:39:02.619000 Updating...
2018-04-08 12:39:02.690000 Init error
2018-04-08 12:39:02.697000 srv_supervisor_thread start
2018-04-08 12:39:02.704000 srv_supervisor_thread terminated
2018-04-08 12:39:02.710000 Process terminated with exit code 1
2018-04-08 12:39:02.718000 Launched python -u C:\Users\Egor\Desktop\kopter\run_folder\main.py
2018-04-08 12:39:02.797000 Init error
2018-04-08 12:39:02.804000 Main run...
2018-04-08 12:39:02.812000 
2018-04-08 12:39:02.885000 Starting threads...
2018-04-08 12:39:07.095000 Launcher terminating...
2018-04-08 13:07:41.606000 Launched python -u C:\Users\Egor\Desktop\kopter\run_folder\main.py
2018-04-08 13:07:41.689000 Init error
2018-04-08 13:07:41.696000 Main run...
2018-04-08 13:07:41.704000 
2018-04-08 13:07:41.787000 Starting threads...
2018-04-08 13:07:41.801000 try update
2018-04-08 13:07:41.815000 Updating...
2018-04-08 13:07:41.888000 Init error
2018-04-08 13:07:41.899000 srv_supervisor_thread start
2018-04-08 13:07:41.907000 srv_supervisor_thread terminated
2018-04-08 13:07:41.914000 Process terminated with exit code 0
2018-04-08 13:07:41.921000 Launched python -u C:\Users\Egor\Desktop\kopter\run_folder\main.py
2018-04-08 13:07:41.988000 Init error
2018-04-08 13:07:41.995000 Main run...
2018-04-08 13:07:42.006000 
2018-04-08 13:07:42.074000 Starting threads...
2018-04-08 13:07:57.675000 try update
2018-04-08 13:07:57.683000 Updating...
2018-04-08 13:07:57.748000 Init error
2018-04-08 13:07:57.756000 srv_supervisor_thread start
2018-04-08 13:07:57.763000 srv_supervisor_thread terminated
2018-04-08 13:07:57.770000 Process terminated with exit code 1
2018-04-08 13:07:57.778000 Launched python -u C:\Users\Egor\Desktop\kopter\run_folder\main.py
2018-04-08 13:07:57.859000 Init error
2018-04-08 13:07:57.867000 Main run...
2018-04-08 13:07:57.873000 
2018-04-08 13:07:57.949000 Starting threads...
2018-04-08 13:08:01.176000 try update
2018-04-08 13:08:01.185000 Updating...
2018-04-08 13:08:01.267000 Process Process-2:
2018-04-08 13:08:01.274000 Init error
2018-04-08 13:08:01.281000 srv_interpreter_thread start
2018-04-08 13:08:01.287000 
2018-04-08 13:08:01.294000 Traceback (most recent call last):
2018-04-08 13:08:01.304000 File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
2018-04-08 13:08:01.310000 self.run()
2018-04-08 13:08:01.315000 File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
2018-04-08 13:08:01.322000 self._target(*self._args, **self._kwargs)
2018-04-08 13:08:01.328000 File "C:\Users\Egor\Desktop\kopter\run_folder\main.py", line 182, in srv_interpreter_thread
2018-04-08 13:08:01.334000 client.close()
2018-04-08 13:08:01.341000 AttributeError: 'str' object has no attribute 'close'
2018-04-08 13:08:01.347000 Init error
2018-04-08 13:08:01.353000 srv_supervisor_thread start
2018-04-08 13:08:01.359000 srv_supervisor_thread terminated
2018-04-08 13:08:01.367000 Process terminated with exit code 1
2018-04-08 13:08:01.375000 Launched python -u C:\Users\Egor\Desktop\kopter\run_folder\main.py
2018-04-08 13:08:01.452000 Init error
2018-04-08 13:08:01.460000 Main run...
2018-04-08 13:08:01.466000 
2018-04-08 13:08:01.542000 Starting threads...
2018-04-08 13:08:02.460000 try update
2018-04-08 13:08:02.468000 Updating...
2018-04-08 13:08:02.559000 Init error
2018-04-08 13:08:02.584000 srv_supervisor_thread start
2018-04-08 13:08:02.592000 srv_supervisor_thread terminated
2018-04-08 13:08:02.599000 Process terminated with exit code 1
2018-04-08 13:08:02.607000 Launched python -u C:\Users\Egor\Desktop\kopter\run_folder\main.py
2018-04-08 13:08:02.693000 Init error
2018-04-08 13:08:02.705000 Main run...
2018-04-08 13:08:02.715000 
2018-04-08 13:08:02.795000 Starting threads...
2018-04-08 13:08:06.528000 try update
2018-04-08 13:08:06.538000 Updating...
2018-04-08 13:08:06.613000 Process Process-2:
2018-04-08 13:08:06.626000 Init error
2018-04-08 13:08:06.632000 srv_supervisor_thread start
2018-04-08 13:08:06.638000 srv_supervisor_thread terminated
2018-04-08 13:08:06.646000 Process terminated with exit code 1
2018-04-08 13:08:06.654000 Launched python -u C:\Users\Egor\Desktop\kopter\run_folder\main.py
2018-04-08 13:08:06.738000 Init error
2018-04-08 13:08:06.745000 Main run...
2018-04-08 13:08:06.754000 
2018-04-08 13:08:06.830000 Starting threads...
2018-04-08 13:08:08.048000 try update
2018-04-08 13:08:08.061000 Updating...
2018-04-08 13:08:08.129000 Process Process-2:
2018-04-08 13:08:08.137000 Init error
2018-04-08 13:08:08.145000 srv_interpreter_thread start
2018-04-08 13:08:08.151000 
2018-04-08 13:08:08.157000 Traceback (most recent call last):
2018-04-08 13:08:08.164000 File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
2018-04-08 13:08:08.175000 self.run()
2018-04-08 13:08:08.182000 File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
2018-04-08 13:08:08.188000 self._target(*self._args, **self._kwargs)
2018-04-08 13:08:08.194000 File "C:\Users\Egor\Desktop\kopter\run_folder\main.py", line 182, in srv_interpreter_thread
2018-04-08 13:08:08.202000 client.close()
2018-04-08 13:08:08.208000 AttributeError: 'str' object has no attribute 'close'
2018-04-08 13:08:08.215000 Init error
2018-04-08 13:08:08.222000 srv_supervisor_thread start
2018-04-08 13:08:08.228000 srv_supervisor_thread terminated
2018-04-08 13:08:08.236000 Process terminated with exit code 1
2018-04-08 13:08:08.244000 Launched python -u C:\Users\Egor\Desktop\kopter\run_folder\main.py
2018-04-08 13:08:08.323000 Init error
2018-04-08 13:08:08.332000 Main run...
2018-04-08 13:08:08.340000 
2018-04-08 13:08:08.409000 Starting threads...
